export const BAG_ADD_ITEM = 'BAG_ADD_ITEM';
export const BAG_REMOVE_ITEM = 'BAG_REMOVE_ITEM';
export const BAG_SAVE_SHIPPING_ADDRESS = 'BAG_SAVE_SHIPPING_ADDRESS';
export const BAG_SAVE_PAYMENT_METHOD = 'BAG_SAVE_PAYMENT_METHOD';
export const BAG_RESET_ITEMS = 'BAG_RESET_ITEMS';