export const WISHLIST_ADD_ITEM_REQUEST = 'WISHLIST_ADD_REQUEST';
export const WISHLIST_ADD_ITEM_SUCCESS = 'WISHLIST_ADD_SUCCESS';
export const WISHLIST_ADD_ITEM_FAILURE = 'WISHLIST_ADD_FAILURE';

export const WISHLIST_USER_REQUEST = 'WISHLIST_USER_REQUEST';
export const WISHLIST_USER_SUCCESS = 'WISHLIST_USER_SUCCESS';
export const WISHLIST_USER_FAILURE = 'WISHLIST_USER_FAILURE';